name: Disk Cleanup
runs:
  using: composite
  steps:
  - name: Remove unnecessary files
    if: runner.os == "Linux" || runner.os == "macOS"
    run: |
      rm -rf /usr/share/dotnet
      rm -rf /opt/hostedtoolcache
