name: Disk Cleanup
runs:
  using: composite
  steps:
  - name: Remove unnecessary files
    shell: bash
    if: runner.os == 'Linux' || runner.os == 'macOS'
    run: |
      rm -rf ~/hostedtoolcache
      rm -rf /opt/hostedtoolcache
