name: 'Rust Cache'
description: 'Cache rust dep and build artifacts'
runs:
  using: "composite"
  steps:
  - uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
      key: |
        cargo-deps-${{ hashFiles('**/Cargo.lock') }}
      restore-keys: |
        cargo-deps-
  - uses: actions/cache@v3
    with:
      path: ~/.cargo/target/
      key: |
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}
      restore-keys: |
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-
  - shell: bash
    env:
      SCCACHE_VERSION: v0.4.1
      SCCACHE_FILE: >-
        ${{ (runner.os == 'Linux' && 'sccache-v0.4.1-x86_64-unknown-linux-musl.tar.gz')
        || (runner.os == 'macOS' && 'sccache-v0.4.1-x86_64-apple-darwin.tar.gz')
        || (runner.os == 'Windows' && 'sccache-v0.4.1-x86_64-pc-windows-msvc.tar.gz') }}
      SCCACHE_FILE_SHA256: >-
        ${{ (runner.os == 'Linux' && 'f077d92ca86d71bc55aebeeb6e8dc557fef481446ccc82504aeedf1fe6e1f657')
        || (runner.os == 'macOS' && 'a291f1d90c6b25726866f018ec6071fa4d20ca443ad91fe5dfb9740eb4ebc45a')
        || (runner.os == 'Windows' && '7508cfa20b045a891eba2f7298afb8faec886d40d10b844830160b096fe99874') }}
      SCCACHE_DIR: >-
        ${{ (runner.os == 'Linux' && 'sccache-v0.4.1-x86_64-unknown-linux-musl')
        || (runner.os == 'macOS' && 'sccache-v0.4.1-x86_64-apple-darwin')
        || (runner.os == 'Windows' && 'sccache-v0.4.1-x86_64-pc-windows-msvc') }}
      SCCACHE_BIN_FILE: sccache${{ runner.os == 'Windows' && '.exe' || '' }}
      SHASUM: ${{ runner.os == 'macOS' && 'shasum' || 'sha256sum' }}
    run: |
      curl --fail --location --output /tmp/$SCCACHE_FILE https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/$SCCACHE_FILE
      $SHASUM -c <(echo "$SCCACHE_FILE_SHA256  /tmp/$SCCACHE_FILE")
      mkdir -p "$HOME/.local/bin"
      tar xz -f /tmp/$SCCACHE_FILE -C "$HOME/.local/bin" --strip-components=1 $SCCACHE_DIR/$SCCACHE_BIN_FILE
      chmod +x "$HOME/.local/bin/$SCCACHE_BIN_FILE"
  - shell: bash
    run: |
      echo "RUSTC_WRAPPER=$HOME/.local/bin/sccache${{ runner.os == 'Windows' && '.exe' || '' }}" >> $GITHUB_ENV
      echo 'SCCACHE_CACHE_SIZE=9G' >> $GITHUB_ENV
  - uses: actions/cache@v3
    with:
      path: ~/.cache/sccache
      key: |
        cargo-sccache-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}
      restore-keys: |
        cargo-sccache-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-
        cargo-sccache-${{ github.workflow }}-${{ github.job }}-
  - if: github.ref_protected
    shell: bash
    run: rm -fr ~/.cache/sccache
