name: 'Rust Cache'
description: 'Cache rust dep and build artifacts'

inputs:
  size:
    default: 9G

runs:
  using: "composite"
  steps:
  - uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
      key: |
        cargo-deps-${{ hashFiles('**/Cargo.lock') }}
      restore-keys: |
        cargo-deps-
  - uses: actions/cache@v3
    with:
      path: ~/.cargo/target/
      key: |
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}
      restore-keys: |
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-
  - shell: bash
    env:
      SCCACHE_VERSION: v0.3.0
      SCCACHE_FILE: >-
        ${{ (runner.os == 'Linux' && 'sccache-v0.3.0-x86_64-unknown-linux-musl.tar.gz')
        || (runner.os == 'macOS' && 'sccache-v0.3.0-x86_64-apple-darwin.tar.gz')
        || (runner.os == 'Windows' && 'sccache-v0.3.0-x86_64-pc-windows-msvc.tar.gz') }}
      SCCACHE_FILE_SHA256: >-
        ${{ (runner.os == 'Linux' && 'e6cd8485f93d683a49c83796b9986f090901765aa4feb40d191b03ea770311d8')
        || (runner.os == 'macOS' && '61c16fd36e32cdc923b66e4f95cb367494702f60f6d90659af1af84c3efb11eb')
        || (runner.os == 'Windows' && 'f25e927584d79d0d5ad489e04ef01b058dad47ef2c1633a13d4c69dfb83ba2be') }}
      SCCACHE_DIR: >-
        ${{ (runner.os == 'Linux' && 'sccache-v0.3.0-x86_64-unknown-linux-musl')
        || (runner.os == 'macOS' && 'sccache-v0.3.0-x86_64-apple-darwin')
        || (runner.os == 'Windows' && 'sccache-v0.3.0-x86_64-pc-windows-msvc') }}
      SCCACHE_BIN_FILE: sccache${{ runner.os == 'Windows' && '.exe' || '' }}
      SHASUM: ${{ runner.os == 'macOS' && 'shasum' || 'sha256sum' }}
    run: |
      curl --fail --location --output /tmp/$SCCACHE_FILE https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/$SCCACHE_FILE
      $SHASUM -c <(echo "$SCCACHE_FILE_SHA256  /tmp/$SCCACHE_FILE")
      mkdir -p "$HOME/.local/bin"
      tar xz -f /tmp/$SCCACHE_FILE -C "$HOME/.local/bin" --strip-components=1 $SCCACHE_DIR/$SCCACHE_BIN_FILE
      chmod +x "$HOME/.local/bin/$SCCACHE_BIN_FILE"
  - shell: bash
    run: |
      echo "RUSTC_WRAPPER=$HOME/.local/bin/sccache${{ runner.os == 'Windows' && '.exe' || '' }}" >> $GITHUB_ENV
      echo 'SCCACHE_CACHE_SIZE=${{ inputs.size }}' >> $GITHUB_ENV
      echo 'SCCACHE_GHA_CACHE_TO=cargo-sccache-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}' >> $GITHUB_ENV
  - if: '!github.ref_protected'
    shell: bash
    run: |
      echo 'SCCACHE_GHA_CACHE_FROM=cargo-sccache-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-,cargo-sccache-${{ github.workflow }}-${{ github.job }}-' >> $GITHUB_ENV
