name: 'Rust Cache'
description: 'Cache rust dep and build artifacts'
runs:
  using: "composite"
  steps:
  - uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
      key: |
        cargo-deps-${{ hashFiles('**/Cargo.lock') }}
      restore-keys: |
        cargo-deps-
  - uses: actions/cache@v3
    with:
      path: ~/.cargo/target/
      key: |
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}
      restore-keys: |
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-
  - shell: bash
    env:
      SCCACHE_VERSION: v0.3.0
      SCCACHE_FILE: sccache-v0.3.0-x86_64-unknown-linux-musl.tar.gz
      SCCACHE_FILE_SHA256: e6cd8485f93d683a49c83796b9986f090901765aa4feb40d191b03ea770311d8
      SCCACHE_DIR: sccache-v0.3.0-x86_64-unknown-linux-musl
    run: >
      curl -sSL -o /tmp/$SCCACHE_FILE https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/$SCCACHE_FILE
      sha256sum -c <(echo "$SCCACHE_FILE_SHA256  /tmp/$SCCACHE_FILE")
      tar xz -f /tmp/$SCCACHE_FILE -C /usr/local/bin --strip-components=1 $SCCACHE_DIR/sccache
      chmod +x /usr/local/bin/sccache
  - shell: bash
    run: |
      echo 'RUSTC_WRAPPER=sccache' >> $GITHUB_ENV
      echo 'SCCACHE_CACHE_SIZE=9G' >> $GITHUB_ENV
  - uses: actions/cache@v3
    with:
      path: ~/.cache/sccache
      key: |
        cargo-sccache-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}
      restore-keys: |
        cargo-sccache-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-
        cargo-sccache-${{ github.workflow }}-${{ github.job }}-
  - if: github.ref_protected
    shell: bash
    run: rm -fr ~/.cache/sccache
