name: 'Rust Cache'
description: 'Cache rust dep and build artifacts'
runs:
  using: "composite"
  steps:
  - uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
      key: |
        cargo-deps-${{ hashFiles('**/Cargo.lock') }}
      restore-keys: |
        cargo-deps-
  - uses: actions/cache@v3
    with:
      path: ~/.cargo/target/
      key: |
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}
      restore-keys: |
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-
        cargo-target-global-${{ github.workflow }}-${{ github.job }}-
  - shell: bash
    run: cargo install --target-dir ~/.cargo/target --locked sccache
  - shell: bash
    run: |
      echo 'RUSTC_WRAPPER=sccache' >> $GITHUB_ENV
      echo 'SCCACHE_CACHE_SIZE=9G' >> $GITHUB_ENV
  - uses: actions/cache@v3
    with:
      path: ~/.cache/sccache
      key: |
        cargo-sccache-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-${{ github.sha }}
      restore-keys: |
        cargo-sccache-${{ github.workflow }}-${{ github.job }}-${{ strategy.job-index }}-
        cargo-sccache-${{ github.workflow }}-${{ github.job }}-
  - if: github.ref_protected
    shell: bash
    run: rm -fr ~/.cache/sccache
