name: Update CompletedSprint on Issue Closed

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]


jobs:
  update_completed_sprint:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest completed sprint
        id: get_latest_completed_sprint
        uses: actions/github-script@v5
        with:
          script: |
            const eventName = context.eventName;
            const url = eventName === 'issues' || eventName === 'issue_comment' ?
              payload.issue.html_url :
              payload.pull_request.html_url;
            const { data } = await github.graphql(`
              query {
                resource(url: "${url}") {
                  ... on ${eventName.startsWith('issue') ? 'Issue' : 'PullRequest'} {
                    id,
                    projectV2(number: 37) {
                      id
                      field(name: "CompletedSprint") {
                        id
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `);

            if (!data.resource?.projectV2?.field?.id) {
              console.log("CompletedSprint field not found on this issue/PR").
              return;
            }

            const sprints = data.resource.projectV2.field.options.filter(a =>
              a.name.match(/sprint\s+(\d+)/i)
            ).sort((a, b) => {
              let amatch = Number(a.name.match(/sprint\s+(\d+)/i)[1]);
              let bmatch = Number(b.name.match(/sprint\s+(\d+)/i)[1]);
              if (amatch < bmatch) return -1;
              if (amatch > bmatch) return 1;
              return 0;
            }).reverse();
            if (sprints.length === 0) throw new Error("No last sprints found");

            return {
              item_id: data.resource.id,
              project_id: data.resource.projectV2.id,
              field_id: data.resource.projectV2.field.id,
              sprint_id: sprints[0].id,
            };

      - name: Update CompletedSprint field
        uses: actions/github-script@v5
        with:
          script: |
            const {
              item_id,
              project_id,
              field_id,
              sprint_id,
            } = ${{ steps.get_latest_completed_sprint.outputs }};

            // await github.graphql(`
            console.log(`
              mutation {
                updateProjectV2ItemFieldValue(input: {
                  projectId: "${project_id}",
                  itemId: "${item_id}",
                  fieldId: "${field_id}",
                  value: {
                    singleSelectOptionId: "${sprint_id}"
                  }
                })
              }
            `);
