name: Linting

on:
  push:
  pull_request:

jobs:

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: stellar/binaries@v28
        with:
          name: actionlint
          version: v1.7.1
      - run: actionlint
