name: Test rust-cache

on:
  push:
    branches: [main]
  pull_request:

jobs:


  complete:
    if: always()
    needs: [test-without-strategy, test-with-strategy]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  test:
    uses: ./rust-set-rust-version/workflow.yaml
    secrets:
      GITHUB_TOKEN:
