name: Test rust-cache

on:
  push:
    branches: [main]
  pull_request:

jobs:

  complete:
    if: always()
    needs: [test-without-strategy, test-with-strategy]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  test-without-strategy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./rust-cache

  test-with-strategy:
    strategy:
      matrix:
        value: [1, 2]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./rust-cache
